Public Class clsLangMsg

    Public msg_branch As String = "สาขา"
    Public msg_item_brand As String = "ยี่ห้อสินค้า"
    Public msg_cannotconnect_db As String = "ไม่สามารถติดต่อฐานข้อมูลได้"
    Public msg_cannotdelete As String = "ไม่สามารถลบข้อมูลได้"
    Public msg_cannotsave As String = "ไม่สามารถบันทึกข้อมูลได้"
    Public msg_cannotopen As String = "ไม่สามารถเปิดฐานข้อมูลได้"
    Public msg_closewindow As String = "ปิดหน้าต่าง"
    Public msg_colap As String = "ยุบรวม"
    Public msg_confirm_del As String = "ยืนยันการลบข้อมูลหรือไม่"
    Public msg_confirm_save As String = "ยืนยันการบันทึกข้อมูลหรือไม่"
    Public msg_confirm_close As String = "ยืนยันการปิดหน้าต่างหรือไม่"
    Public msg_confirm_post_interest As String = "ยืนยันการบันทึกดอกเบี้ยหรือไม่"
    Public msg_confirm As String = "ยืนยัน"
    Public msg_credit_card As String = "บัตรเครดิต"
    Public msg_custdisplay_port As String = "จอแสดงราคาต่อกับ"
    Public msg_cust_group As String = "ประเภทสมาชิก"
    Public msg_cust_type As String = "กลุ่มสมาชิก"
    Public msg_delete As String = "ลบข้อมูล"
    Public msg_duplicate As String = "ข้อมูลซ้ำ"
    Public msg_dept As String = "ข้อมูลแผนก"
    Public msg_directprint As String = "พิมพ์โดยตรง"
    Public msg_drawer_port As String = "ลิ้นชักต่อกับ"
    Public msg_error As String = "ข้อผิดพลาด"
    Public msg_expan As String = "แสดงทั้งหมด"
    Public msg_fastprint As String = "พิมพ์แบบเร็ว"
    Public msg_finddata As String = "ค้นข้อมูล"
    Public msg_findfrom As String = "ค้นหาจาก"
    Public msg_id As String = "รหัส"
    Public msg_img_path As String = "ที่เก็บรูป"
    Public msg_infomation As String = "ข้อมูล"
    Public msg_invalidtype As String = "ชนิดข้อมูลไม่ถูกต้อง"
    Public msg_invaliddata As String = "ข้อมูลไม่ถูกต้อง"
    Public msg_item As String = "สินค้า"
    Public msg_item_group As String = "กลุ่มสินค้า"
    Public msg_item_grade As String = "เกรดสินค้า"
    Public msg_item_type As String = "ประเภทสินค้า"
    Public msg_item_uom As String = "หน่วยนับ"
    Public msg_itemlist As String = "แสดงรายการข้อมูล"
    Public msg_location As String = "ที่เก็บสินค้า"
    Public msg_name As String = "ชื่อ"
    Public msg_new As String = "เพิ่มรายการ"
    Public msg_nodata As String = "ไม่มีข้อมูลในฐานข้อมูล"
    Public msg_noprint As String = "ไม่พิมพ์"
    Public msg_percnt_disct As String = "ส่วนลด (%)"
    Public msg_pos_machine As String = "เครื่องคิดเงิน"
    Public msg_printbyform As String = "พิมพ์โดยใช้ฟอร์ม"
    Public msg_printer_port As String = "เครื่องพิมพ์ต่อกับ"
    Public msg_refresh As String = "โหลดข้อมูลใหม่"
    Public msg_report As String = "รายงาน"
    Public msg_save As String = "บันทึก"
    Public msg_savesuccess As String = "บันทึกข้อมูลเรียบร้อยแล้ว"
    Public msg_deletesuccess As String = "ลบข้อมูลเรียบร้อยแล้ว"
    Public msg_testing As String = "ทดสอบ"
    Public msg_totalrows As String = "จำนวนรายการ"
    Public msg_saleman As String = "พนักงานขาย"
    Public msg_slip_msg As String = "ข้อความหัวท้ายใบเสร็จ"
    Public msg_slip_msg_hd As String = "ข้อความหัวใบเสร็จ"
    Public msg_slip_msg_dt As String = "ข้อความท้ายใบเสร็จ"
    Public msg_use_drawer As String = "ใช้ลิ้นชักหรือไม่"
    Public msg_use_custdisplay As String = "ใช้จอแสดงราคาหรือไม่"
    Public msg_vend_type As String = "ประเภทผู้จำหน่าย"
    Public msg_warehouse As String = "คลังสินค้า"
    Public msg_warning As String = "คำเตือน"
    Public msg_cannot_edit As String = "ไม่สามารถแก้ไขข้อมูลนี้ได้"
    Public msg_cannot_delete As String = "ไม่สามารถลบข้อมูลนี้ได้"
    Public msg_open_data As String = "กำลังแสดงข้อมูล"

    Public msg_name2 As String = "ชื่ออังกฤษ"
    Public msg_shortname As String = "ชื่อย่อ"
    Public msg_costtype As String = "ประเภทต้นทุน"
    Public msg_ordleadtime As String = "ระยะเวลาสั่งซื้อ"
    Public msg_remark As String = "หมายเหตุ"
    Public msg_minimum As String = "จุดต่ำสุด"
    Public msg_itemsize As String = "ขนาด"
    Public msg_weight As String = "น้ำหนัก"
    Public msg_std_cost As String = "ต้นทุนมาตรฐาน"
    Public msg_fifo_cost As String = "ต้นทุน FIFO"
    Public msg_avg_cost As String = "ต้นทุนเฉลี่ย"
    Public msg_stdsale_price As String = "ราคามาตรฐาน"
    Public msg_stduom As String = "หน่วยนับย่อย"
    Public msg_sale_price As String = "ราคาขาย"
    Public msg_return As String = "การคืนสินค้า"
    Public msg_sale As String = "การขายสินค้า"
    Public msg_buytax As String = "ภาษีขาย"
    Public msg_saletax As String = "ภาษีซื้อ"
    Public msg_vendor As String = "ผู้จำหน่าย"
    Public msg_size As String = "ขนาด"

    Public msg_lot_control As String = "ควาบคุมล็อท"
    Public msg_multi_uom As String = "หลายหน่วยนับ"
    Public msg_serial_control As String = "ควบคุม Serial"
    Public msg_special_control As String = "ควบคุมพิเศษ"
    Public msg_stock_control As String = "ควาบคุมสต็อก"

    Public msg_copy As String = "คัดลอก"
    Public msg_barcode As String = "บาร์โค้ด"
    Public msg_uom As String = "หน่วยนับ"
    Public msg_ratio As String = "อัตราส่วน"
    Public msg_onhand_bylot As String = "คงเหลือตามล็อท"
    Public msg_onhand_bywh As String = "คงเหลือตามคลัง"
    Public msg_packing_size As String = "ขนาดบรรจุ"

    Public msg_job As String = "อาชีพ"
    Public msg_rec_type As String = "ประเภทการรับ"
    Public msg_iss_type As String = "ประเภทการจ่าย"
    Public msg_registno As String = "เลขที่จดทะเบียน"

    Public msg_need_save As String = "ยังไม่บันทึกข้อมูล" & vbCrLf & "ต้องการบันทึกข้อมูลหรือไม่"
    Public msg_used_price As String = "ใช้ราคาที่"
    Public msg_cardno As String = "บัตรประชาชน"
    Public msg_phoneno As String = "โทรศัพท์"
    Public msg_address As String = "ที่อยู่"
    Public msg_age As String = "อายุ"
    Public msg_amphur As String = "อำเภอ"
    Public msg_poscode As String = "รหัสไปรษณีย์"
    Public msg_birth_date As String = "วันเกิด"
    Public msg_card_begin As String = "วันออกบัตร"
    Public msg_card_exp As String = "วันบัตรหมดอายุ"
    Public msg_contry As String = "ประเทศ"
    Public msg_fax As String = "แฟกซ์"
    Public msg_province As String = "จังหวัด"
    Public msg_reg_date As String = "วันสมัคร"
    Public msg_vocation As String = "อาชีพ"
    Public msg_sex As String = "เพศ"
    Public msg_member As String = "ข้อมูลสมาชิก"
    Public msg_image As String = "รูปภาพ"
    Public msg_prefix_name As String = "คำนำหน้า"
    Public msg_female As String = "หญิง"
    Public msg_male As String = "ชาย"
    Public msg_customer As String = "ลูกค้า"
    Public msg_status As String = "สถานะ"

    Public msg_receive As String = "การรับสินค้า"
    Public msg_rec_no As String = "เลขที่การรับ"
    Public msg_contact As String = "ข้อมูลการติดต่อ"
    Public msg_receiv_from As String = "รับจาก"
    Public msg_rec_date As String = "วันรับ"
    Public msg_ref_date As String = "วันที่อ้างอิง"
    Public msg_ref_no As String = "เลขที่อ้างอิง"

    Public msg_issue As String = "การจ่ายสินค้า"
    Public msg_issue_no As String = "เลขที่การจ่าย"
    Public msg_issue_to As String = "จ่ายให้"
    Public msg_issue_date As String = "วันจ่าย"

    Public msg_amount As String = "จำนวนเงิน"
    Public msg_lot_no As String = "ล็อท"
    Public msg_unit_price As String = "ราคาต่อหน่วย"
    Public msg_procuct_price As String = "ราคาสินค้า"
    Public msg_qty As String = "จำนวน"
    Public msg_serial_no As String = "Serial no"
    Public msg_trn_type As String = "ประเภทเอกสาร"
    Public msg_trn_group As String = "กลุ่มเอกสาร"
    Public msg_discount_text As String = "ส่วนลด"
    Public msg_discount As String = "ส่วนลด"
    Public msg_auto_number As String = "เลขอัตโนมัติ"
    Public msg_is_free As String = "เป็นของแถม"
    Public msg_total As String = "รวมทั้งสิ้น"

    Public msg_vat_type As String = "ชนิดภาษี"
    Public msg_vat_rate As String = "อัตราภาษี"
    Public msg_vat_amount As String = "ภาษีมูลค่าเพิ่ม"
    Public msg_vat_include As String = "สินค้ารวมภาษี"      '//0
    Public msg_vat_exclude As String = "สินค้าแยกภาษี"     '//1
    Public msg_vat_novat As String = "สินค้าไม่คิดภาษี"      '//2

    Public msg_wh_tras As String = "การย้ายคลังสินค้า"
    Public msg_wh_from As String = "จากคลัง"
    Public msg_wh_to As String = "เข้าคลัง"
    Public msg_loc_from As String = "ที่เก็บต้นทาง"
    Public msg_loc_to As String = "ที่เก็บปลายทาง"
    Public msg_doc_date As String = "วันที่เอกสาร"
    Public msg_doc_no As String = "เลขที่เอกสาร"

    Public msg_comp_name As String = "ชื่อบริษัท"
    Public msg_owner_name As String = "ชื่อผู้ประกอบการ"
    Public msg_tax_no As String = "เลขที่ผู้เสียภาษี"
    Public msg_company As String = "ข้อมูลบริษัท"
    Public msg_shop_name As String = "ขื่อร้าน"

    Public msg_prj As String = "โครงการ"
    Public msg_dep_type As String = "ประเภทการฝาก"
    Public msg_bank_adj_type As String = "ประเภทการปรับปรุงยอด"
    Public msg_bank_adj_increment As String = "ปรับปรุงยอดเพิ่ม"
    Public msg_bank_adj_decrement As String = "ปรับปรุงยอดลด"
    Public msg_mas_data As String = "ข้อมูลหลัก"
    Public msg_main_menu As String = "เมนูหลัก"
    Public msg_deposit_money As String = "ฝากเงิน"
    Public msg_deposit As String = "เงินฝาก"
    Public msg_deposit_interest_ratio As String = "อัตราดอกเบี้ย"
    Public msg_create_account As String = "เปิดบัญชี"
    Public msg_draw_money As String = "ถอนเงิน"
    Public msg_pay_fee As String = "ค่าธรรมเนียม"
    Public msg_pay_interest As String = "จ่ายดอกเบี้ยเงินฝากค้างจ่าย"
    Public msg_cal_interest As String = "คำนวนดอกเบี้ย"
    Public msg_deposit_report As String = "รายงานเกี่ยวกับเงินฝาก"
    Public msg_interest_ratio As String = "อัตราดอกเบี้ย"
    Public msg_date_cal_to As String = "คำนวณถึงวันที่"

    Public msg_makecap As String = "สวัสดิการ"
    Public msg_add_share As String = "เพิ่มหุ้น"
    Public msg_remove_share As String = "ถอนหุ้น"
    Public msg_makecap_type As String = "ประเภทสวัสดิการ"
    Public msg_makecap_cost As String = "มูลค่า"  '//เบี้ยประกัน
    Public msg_makecap_member As String = "สมาชิกกองทุนสวัสดิการ"
    Public msg_makecap_invoice As String = "ออกใบแจ้งหนี้ค่าสวัสดิการ"
    Public msg_makecap_receive As String = "รับชำระค่าสวัสดิการ"
    Public msg_makecap_report As String = "รายงานเกี่ยวกับสวัสดิการ"

    Public msg_loan As String = "สินเชื่อ"
    Public msg_loan_contract_no As String = "เลขที่สัญญา"
    Public msg_loan_contract_date As String = "วันที่ทำสัญญา"
    Public msg_loan_money_paid As String = "เงินต้น"
    Public msg_loan_to_pay As String = "เงินต้นพึงชำระ"
    Public msg_loan_money As String = "วงเงินกู้"
    Public msg_loan_balance As String = "หนี้คงค้าง"
    Public msg_loan_old_db_balance As String = "ดอกเบี้ยค้าง"
    Public msg_loan_db_balance As String = "ดอกเบี้ย"
    Public msg_loan_old_fine_balance As String = "ค่าปรับค้าง"
    Public msg_loan_fine_balance As String = "ค่าปรับ"
    Public msg_loan_app_doc As String = "การประชุมครั้งที่"
    Public msg_loan_app_no As String = "ครั้งที่"
    Public msg_loan_objective As String = "กู้เพื่อ"
    Public msg_loan_land_type As String = "ชื่อผู้ส่ง"
    Public msg_loan_land_group As String = "ประเภทที่ดิน"
    Public msg_loan_land_info As String = "ข้อมูลที่ดิน"
    Public msg_loan_type As String = "ข้อมูลสิ่งของบริจาค"
    Public msg_loan_project As String = "โครงการเงินกู้"
    Public msg_loan_interest As String = "อัตราดอกเบี้ยเงินกู้"
    Public msg_loan_member_level As String = "ลำดับชั้นสมาชิก"
    Public msg_loan_contract As String = "สัญญาเงินกู้"
    Public msg_guarantor As String = "ผู้ค้ำประกัน"
    Public msg_loan_pay As String = "จ่ายเงินกู้"
    Public msg_loan_pay_manual As String = "จ่ายเงินกู้เครดิตเงินสด"
    Public msg_loan_pay_cash As String = "เงินสด"
    Public msg_loan_pay_credit As String = "เงินโอน"
    Public msg_loan_cancel_pay As String = "ยกเลิกการจ่ายเงินกู้"
    Public msg_loan_warning As String = "ใบเตือนหนี้"
    Public msg_loan_paid As String = "เงินกู้จ่ายแล้ว"
    Public msg_loan_int_cal As String = "คำนวณดอกเบี้ย"
    Public msg_loan_receipt As String = "รับชำระเงิน"
    Public msg_loan_rec_cash As String = "ชำระเงินสด"
    Public msg_loan_rec_credit As String = "ชำระเงินโอน"
    Public msg_loan_rec_paid_daily As String = "สรุปรายวันรับจ่าย"
    Public msg_loan_report As String = "รายงานเกี่ยวกับสินเชื่อ"
    Public msg_loan_garantor As String = "ตรวจสอบบุคคลค้ำประกัน"
    Public msg_loan_garaty_amount As String = "วงเงิน"
    Public msg_loan_period As String = "กำหนดชำระ"
    Public msg_loan_period_no As String = "รอบที่"
    Public msg_loan_period_date As String = "กำหนดชำระ"
    Public msg_loan_period_pay As String = "จำนวนเงิน"
    Public msg_loan_period_paid As String = "ชำระแล้ว"
    Public msg_loan_fine_rate As String = "เปอร์เซ็นต์การปรับ"
    Public msg_loan_grade As String = "เกรด"
    Public msg_loan_rate1 As String = "AA"
    Public msg_loan_rate2 As String = "A"
    Public msg_loan_rate3 As String = "B"
    Public msg_loan_rate4 As String = "C"
    Public msg_loan_rate5 As String = "D"
    Public msg_loan_land_add1 As String = "อำเภอ"
    Public msg_loan_land_add2 As String = "ตำบล"
    Public msg_loan_land_id As String = "ที่ดินเลขที่"
    Public msg_loan_land_book As String = "เล่มที่"
    Public msg_loan_land_page As String = "หน้าที่"
    Public msg_loan_size1 As String = "ไร่"
    Public msg_loan_size2 As String = "งาน"
    Public msg_loan_size3 As String = "ตารางวา"
    Public msg_loan_mgt_date As String = "วันที่"
    Public msg_loan_land_owner As String = "ผู้จำนอง"
    Public msg_loan_land_price As String = "ราคาประเมิณ"
    Public msg_loan_mgt_price As String = "ราคาจำนอง"
    Public msg_loan_page As String = "หน้า"
    Public msg_success_int_cal As String = "คำนวนดอกเบี้ยและค่าปรับเรียบร้อยแล้ว"
    Public msg_money_type_cash As String = "เงินสด"
    Public msg_money_type_credit As String = "เงินเชื่อ"
    Public msg_money_type_all As String = "รวมทุกประเภท"


    Public msg_rpt_loan As String = "รายงานสินเชื่อ"
    Public msg_rpt_loan_member_list As String = "รายการลูกหนี้คงค้าง"
    Public msg_rpt_loan_rec_pay_sum_daily As String = "สรุปรายการรายวันรับ/จ่ายเงินกู้"
    Public msg_rpt_loan_rec_daily As String = "รายงานรายวันรับชำระเงินกู้"
    Public msg_rpt_loan_pay_daily As String = "รายงานรายวันจ่ายเงินกู้"
    Public msg_rpt_loan_rec_monthly As String = "รายงานรายเดือนรับชำระเงินกู้"
    Public msg_rpt_loan_pay_monthly As String = "รายงานรายเดือนจ่ายเงินกู้"
    Public msg_rpt_loan_aging As String = "รายงานรายอายุหนี้เงินกู้"
    Public msg_print_rec_slipt As String = "พิมพ์ใบเสร็จรับเงิน"



    Public msg_member_report As String = "รายงานสมาชิกสหกรณ์"
    Public msg_pay_dividends As String = "จ่ายเงินปันผล"
    Public msg_member_code As String = "รหัสสมาชิก"
    Public msg_member_name As String = "ชื่อสมาชิก"
    Public msg_share_price As String = "ราคาหุ้น"
    Public msg_ref_person As String = "ผู้แนะนำ"
    Public msg_resign_date As String = "วันที่ลาออก"
    Public msg_share_total As String = "จำนวนหุ้น"
    Public msg_share_value As String = "มูลค่า"
    Public msg_share_carry_down As String = "ยอดหุ้นยกมา"
    Public msg_share_carry_forwrd As String = "ยอดหุ้นคงเหลือ"
    Public msg_cal_dividends As String = "คำนวนเงินปันผล"
    Public msg_father As String = "ชื่อบิดา"
    Public msg_mather As String = "ชื่อมารดา"
    Public msg_family_qty As String = "จำนวนสมาชิก"
    Public msg_child_qty As String = "จำนวนบุตร"
    Public msg_child_educate As String = "บุตรกำลังศึกษา"
    Public msg_person As String = "คน"
    Public msg_mary_info As String = "ข้อมูลการสมรส"
    Public msg_couple_name As String = "ชื่อคู่สมรส"
    Public msg_mary_reg_no As String = "เลขทะเบียนสมรส"
    Public msg_mary_reg_date As String = "ลงวันที่"
    Public msg_mary_reg_at1 As String = "จดที่อำเถอ"
    Public msg_mary_reg_at2 As String = "ที่จังหวัด"
    Public msg_data_not_complete As String = "ข้อมูลไม่สมบูรณ์"
    Public msg_acc_no As String = "เลขที่บัญชี"
    Public msg_text_bath As String = "จำนวนเงินตัวอักษร"
    Public msg_money_qty As String = "จำนวนเงิน"
    Public msg_acc_info As String = "ข้อมูลบัญชีเงินฝาก"
    Public msg_draw_person As String = "ผู้มีสิทธิ์ถอน"

    Public msg_cust_id As String = "รหัสลูกค้า"
    Public msg_cust_name As String = "ชื่อลูกค้า"
    Public msg_bank_trn_type As String = "ประเภท"
    Public msg_carry_down As String = "ยอดยกมา"
    Public msg_carry_forwrd As String = "ยอดยกไป"

    Public msg_user As String = "ผู้ใช้งาน"
    Public msg_interest As String = "ดอกเบี้ย"
    Public msg_makecap_mem_info As String = "ข้อมูลสมาชิกสวัสดิการ"
    Public msg_makecap_person As String = "รายชื่อผู้รับผลประโยชน์"
    Public msg_pay_money As String = "ชำระเงิน"
    Public msg_member_relate As String = "เกี่ยวข้องเป็น"
    Public msg_makecap_status As String = "สถานะ"
    Public msg_print_cover As String = "พิมพ์สมุด"
    Public msg_insert_slip_paper As String = "ป้อนกระดาษสลิป"
    Public msg_insert_pass_book As String = "ป้อนสมุดเงินฝาก"
    Public msg_inter_row As String = "กรอกหมายเลขบรรทัดของสมุดที่ต้องการพิมพ์"
    Public msg_balance_amount As String = "ยอดคงเหลือ"

    Public msg_user_data As String = "ข้อมูลผู้ใช้งาน"
    Public msg_user_id As String = "รหัสผู้ใช้งาน"
    Public msg_user_name As String = "ชื่อผู้ใช้งาน"
    Public msg_password As String = "รหัสผ่าน"
    Public msg_no_permission As String = "ไม่มีสิทิ์ใช้งาน"

    Public msg_rpt_criteria As String = "เงื่อนไขการออกรายงาน"
    Public msg_rpt_bank As String = "รายงานเงินฝาก"
    Public msg_rpt_bank_daily As String = "รายงานเงินฝากรายวัน"
    'Public msg_rpt_bank_daily_by_desc As String = "รายงานฝาก/ถอนตามประเภท"
    Public msg_rpt_bank_daily_by_user As String = "รายงานรายวันฝาก/ถอนตามเจ้าหน้าที่"
    Public msg_rpt_bank_daily_by_type As String = "รายงานรายวันฝาก/ถอนตามประเภทบัญชี"
    Public msg_rpt_bank_daily_by_memgroup As String = "รายงานรายวันฝาก/ถอนตามกลุ่มสมาชิก"
    Public msg_rpt_bank_daily_by_sum As String = "รายงานรายวันฝาก/ถอน"
    Public msg_rpt_bank_daily_adjust As String = "รายงานปรับปรุงยอดฝากถอน"
    Public msg_rpt_bank_money_balance As String = "สรุปรายงานเงินฝากอมทรัพย์คงเหลือ"
    Public msg_rpt_bank_money_balance_by_group As String = "สรุปรายงานเงินฝากอมทรัพย์คงเหลือตามกลุ่ม"

    Public msg_rpt_share As String = "รายงานหุ้นและสมาชิก"
    Public msg_rpt_share_daily As String = "รายงานเพิ่มถอนหุ้นรายวัน"
    Public msg_rpt_share_monthly As String = "รายงานเพิ่มถอนหุ้นรายเดือน"
    Public msg_rpt_share_balance As String = "รายงานหุ้นคงเหลือ"
    Public msg_rpt_share_balance_bygroup As String = "รายงานสรุปหุ้นคงเหลือตามกลุ่ม"
    'Public msg_rpt_share_daily_by_group As String = "รายงานฝากถอนหุ้นแบ่งตามกลุ่ม"
    Public msg_rpt_share_holder As String = "รายงานผู้ถือหุ้น"
    Public msg_rpt_share_holder_bygroup As String = "รายงานผู้ถือหุ้นแบ่งตามกลุ่ม"



    Public msg_calculator As String = "เครื่องคิดเลข"
    Public msg_exist_data As String = "ข้อมูลซ้ำ"
    Public msg_confirm_change_code As String = "ยืนยันการเปลี่ยนรหัสเป็น"
    Public msg_enter_new_data As String = "กรอกข้อมูลใหม่"
    Public msg_month_year As String = "เดือน/ปี (ดด/ปปปป)"
    Public msg_from As String = "จาก"
    Public msg_to As String = "ถึง"
    Public msg_no_of_date As String = "จำนวนวัน"

    Public msg_db_cf_amount As String = "ยอดหนี้ยกมา"
    Public msg_rec_amount As String = "ยอดชำระ"
    Public msg_db_rem_amount As String = "ยอดหนี้ค้างรับ"
    Public msg_adv_amount As String = "เงินรับล่วงหน้า"

    Public msg_rpt_fun As String = "รายงานสวัสดิการ"
    Public msg_rpt_fun_daily As String = "รายงานยอดเงินบริจาคระหว่างวัน"
    Public msg_rpt_fun_member_daily As String = "รายงานยอดเคลื่อนไหวสมาชิก"
    Public msg_rpt_fun_monthly As String = "รายงานยอดเงินบริจาคระหว่างเดือน"
    Public msg_rpt_fun_sum_bygroup As String = "รายงานยอดเงินบริจาครายกลุ่ม"
    Public msg_rpt_fun_debt_inform As String = "ใบแจ้งหนี้ค้างจ่าย"
    Public msg_year_month As String = "ปี/เดือน (ปปปป/ดด)"





    Public Function RefreshLanguage() As Boolean

    End Function

    Public Sub New()
        Call RefreshLanguage()
    End Sub
End Class
