'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MBOOK
    Public Property BOOK_ID As String
    Public Property BOOK_DESC As String
    Public Property ENG_DESC As String
    Public Property BOOK_FORM As String
    Public Property BOOK_CASE As String
    Public Property PRT_FORM As String
    Public Property GL_FORM As String
    Public Property PREFIX As String
    Public Property CURR_NO As Nullable(Of Double)
    Public Property POSTFIX As String
    Public Property LEN_NO As Nullable(Of Double)
    Public Property CAL_VAT_FG As String
    Public Property VAT_RATE As Nullable(Of Double)
    Public Property PASSWORD As String
    Public Property BOOK_STCK As String
    Public Property BOOK_TYPE As String

End Class
