'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MCUST
    Public Property ID As String
    Public Property NAME As String
    Public Property TITLE As String
    Public Property ENG_NAME As String
    Public Property REGION As String
    Public Property COLL_DAYS As Nullable(Of Double)
    Public Property CR_DAYS As Nullable(Of Double)
    Public Property CR_LIMIT As Nullable(Of Double)
    Public Property CR_LIMIT_D As Nullable(Of Date)
    Public Property CR_HIST1 As Nullable(Of Double)
    Public Property CR_HIST1_D As Nullable(Of Date)
    Public Property CR_HIST2 As Nullable(Of Double)
    Public Property CR_HIST2_D As Nullable(Of Date)
    Public Property B_F_BK_AMT As Nullable(Of Double)
    Public Property B_F_AMT As Nullable(Of Double)
    Public Property INV_NOSPRE As Nullable(Of Double)
    Public Property BAL_AMTPRE As Nullable(Of Double)
    Public Property BAL_AMT As Nullable(Of Double)
    Public Property BAL_ADV As Nullable(Of Double)
    Public Property CR_BAL_CSH As Nullable(Of Double)
    Public Property CR_BAL_CHQ As Nullable(Of Double)
    Public Property INT_RATE As Nullable(Of Double)
    Public Property INT_EXIN As Nullable(Of Double)
    Public Property STATUS As String
    Public Property TYPE_1 As String
    Public Property TYPE_2 As String
    Public Property SALE_ID As String
    Public Property SHIP_NAME As String
    Public Property SH_NAME As String
    Public Property SH_ADDRESS As String
    Public Property SH_TAMBON As String
    Public Property SH_AMPHUR As String
    Public Property SH_CITY As String
    Public Property SH_ZIP As String
    Public Property SHIP_PHONE As String
    Public Property SH_TEL_EXT As String
    Public Property SH_TEL_2 As String
    Public Property SHIP_FAX As String
    Public Property SH_RATE As Nullable(Of Double)
    Public Property SH_TAX As String
    Public Property SH_BRANCH As Nullable(Of Double)
    Public Property SH_DESC As String
    Public Property ADDRESS As String
    Public Property TAMBON As String
    Public Property AMPHUR As String
    Public Property CITY As String
    Public Property ZIPCODE As String
    Public Property CITY_ID As String
    Public Property AMP_ID As String
    Public Property TAMBON_ID As String
    Public Property PHONE As String
    Public Property PHONE_EXT As String
    Public Property PHONE_2 As String
    Public Property FAX As String
    Public Property E_MAIL As String
    Public Property LAST_SA As Nullable(Of Date)
    Public Property RATE_PRICE As Nullable(Of Double)
    Public Property RATE_VAT As Nullable(Of Double)
    Public Property RATE_DISC1 As Nullable(Of Double)
    Public Property RATE_DISC2 As Nullable(Of Double)
    Public Property RATE_DISC3 As Nullable(Of Double)
    Public Property ID_1 As String
    Public Property ID_2 As String
    Public Property ID_3 As String
    Public Property ID_4 As String
    Public Property NOS_PAY As Nullable(Of Double)
    Public Property AMT_P_PAY As Nullable(Of Double)
    Public Property BIRTH_DATE As Nullable(Of Date)
    Public Property SPEC_DATE As Nullable(Of Date)
    Public Property COMM_AMT As Nullable(Of Double)
    Public Property COMM_RATE As Nullable(Of Double)
    Public Property CHG_RATE As String
    Public Property ACC_CODE As String
    Public Property DEPART_ID As String
    Public Property INV_COUNT As Nullable(Of Double)
    Public Property HIST As String
    Public Property FLAG As String
    Public Property OFF_HOUR As String
    Public Property WARNING As String
    Public Property AMT_HIST1 As Nullable(Of Double)
    Public Property AMT_HIST2 As Nullable(Of Double)
    Public Property QRTN_HIST1 As Nullable(Of Double)
    Public Property QRTN_HIST2 As Nullable(Of Double)
    Public Property QRTN_TIME1 As Nullable(Of Double)
    Public Property QRTN_TIME2 As Nullable(Of Double)
    Public Property AVG_RV As Nullable(Of Double)
    Public Property ACTION As String
    Public Property DELE_DATE As Nullable(Of Date)
    Public Property KEYACCOUNT As String
    Public Property DISC_AMT1 As Nullable(Of Double)
    Public Property DISC_AMT2 As Nullable(Of Double)
    Public Property DISC_AMT3 As Nullable(Of Double)
    Public Property DISC_AMT4 As Nullable(Of Double)
    Public Property DISC_AMT5 As Nullable(Of Double)
    Public Property DISC_ID1 As String
    Public Property DISC_ID2 As String
    Public Property DISC_ID3 As String
    Public Property DISC_ID4 As String
    Public Property DISC_ID5 As String
    Public Property DISC_1 As Nullable(Of Double)
    Public Property DISC_2 As Nullable(Of Double)
    Public Property DISC_3 As Nullable(Of Double)
    Public Property DISC_4 As Nullable(Of Double)
    Public Property DISC_5 As Nullable(Of Double)
    Public Property RTN_CHQ_FG As String
    Public Property TAX_ID As String
    Public Property BRANCH_NO As Nullable(Of Double)
    Public Property BRANCHNAME As String
    Public Property ATTN_NAME As String
    Public Property POSITION As String
    Public Property POSITION_1 As String
    Public Property CONTACT_1 As String
    Public Property POSITION_2 As String
    Public Property CONTACT_2 As String
    Public Property POSITION_3 As String
    Public Property CONTACT_3 As String
    Public Property POSITION_4 As String
    Public Property CONTACT_4 As String
    Public Property POSITION_5 As String
    Public Property CONTACT_5 As String
    Public Property POSITION_6 As String
    Public Property CONTACT_6 As String
    Public Property POSITION_7 As String
    Public Property CONTACT_7 As String
    Public Property POSITION_8 As String
    Public Property CONTACT_8 As String
    Public Property POSITION_9 As String
    Public Property CONTACT_9 As String
    Public Property POSITION10 As String
    Public Property CONTACT10 As String
    Public Property TEL_1 As String
    Public Property TEL_2 As String
    Public Property TEL_3 As String
    Public Property TEL_4 As String
    Public Property TEL_5 As String
    Public Property TEL_6 As String
    Public Property TEL_7 As String
    Public Property TEL_8 As String
    Public Property TEL_9 As String
    Public Property TEL_10 As String
    Public Property SHIP_ID As String
    Public Property NOTES_RV As String
    Public Property ISUPDATE As String
    Public Property CARD_ID As String
    Public Property SIGN_LOCA As String
    Public Property CARDSTART As Nullable(Of Date)
    Public Property CARDEND As Nullable(Of Date)
    Public Property CASH_DISC As Nullable(Of Double)
    Public Property CARD_DISC As Nullable(Of Double)
    Public Property SENDMAIL As String
    Public Property ACTIVE As String
    Public Property G1_COMP As String
    Public Property G1_CONTACT As String
    Public Property G1_ADDRESS As String
    Public Property G1_AMPHUR As String
    Public Property G1_TAMBON As String
    Public Property G1_CITY As String
    Public Property G1_ZIPCODE As String
    Public Property G1_PHONE As String
    Public Property G1_ID As String
    Public Property G2_COMP As String
    Public Property G2_CONTACT As String
    Public Property G2_ADDRESS As String
    Public Property G2_AMPHUR As String
    Public Property G2_TAMBON As String
    Public Property G2_CITY As String
    Public Property G2_ZIPCODE As String
    Public Property G2_PHONE As String
    Public Property G2_ID As String
    Public Property id_no As Integer

End Class
