'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MSTK_BR
    Public Property ID As String
    Public Property NAME As String
    Public Property REGION As String
    Public Property STATUS As String
    Public Property TYPE_1 As String
    Public Property ADDRESS As String
    Public Property TAMBON As String
    Public Property AMPHUR As String
    Public Property CITY As String
    Public Property ZIPCODE As String
    Public Property ENG_NAME As String
    Public Property PHONE As String
    Public Property PHONE_EXT As String
    Public Property PHONE_2 As String
    Public Property FAX As String
    Public Property HIST As String
    Public Property LEN_CODE As Nullable(Of Double)
    Public Property ACC_CODE As String
    Public Property FLAG As String
    Public Property ACTION As String

End Class
