'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class N_CUST_SALE_SLIP_TRAN
    Public Property CUST_ID As String
    Public Property SALE_SLIP_ID As String
    Public Property DETAIL As String
    Public Property STK_ID As String
    Public Property QTY As Nullable(Of Integer)
    Public Property PROD_CODE As String
    Public Property ID As Integer
    Public Property CREATEDATE As Nullable(Of Date)
    Public Property UPDATEDATE As Nullable(Of Date)
    Public Property PRICE As Nullable(Of Decimal)
    Public Property AMOUNT As Nullable(Of Decimal)

End Class
